### ISSUE TITLE
Differentiate between links and inline code snippets

### ISSUE THREAD

**Issue by happyRip** [TheThingsIndustries/lorawan-stack-docs#1004]
#### Summary

Inline code snippets look very similar to text hyperlinks.
<img width="843" alt="image" src="https://user-images.githubusercontent.com/73070465/204585939-b366c244-0c44-4e3e-a66b-6d4d25e8499c.png">
If I haven't told you red border highlights links and green boxes highlight normal text, you probably couldn't tell yourself. Either the first code snippet would be considered a standard text, or the bottom ones would be assumed to be hyperlinks. 

#### Why do we need this ?

It's hard to distinguish between links and inline code snippets.

#### What is already there? What do you see now?

Hyperlinked text is blue. Inline code snippet text is blue.

#### What is missing? What do you want to see?

We could add a hyperlink icon indicating the text is a hyperlink. We could also change the colour of inline code snippet text e.g. to black to match block snippet text colour.

Example of the first one is in [Hugo docummentation](https://gohugo.io/getting-started/quick-start/#prerequisites):
<img width="499" alt="image" src="https://user-images.githubusercontent.com/73070465/204587062-65f3c3a6-4681-4382-a576-b6328033be46.png">

#### How do you propose to ~~document~~ implement this?

Depends on the chosen solution.

#### Can you do this yourself and submit a Pull Request?

I could submit a PR if a solution would be decided on.

**Comment by NicolasMrad** [comment]
@pierrephz any feedback you want to give here on how to proceed?
