### ISSUE TITLE
Fix search functionality

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsIndustries/lorawan-stack-docs#1012]
#### Summary
We need to fix the search functionality in the docs, indexation needs to be implemented.

#### Why do we need this ?
To make the search functionality better and more efficient

#### What is already there? What do you see now?
As per @adriansmares some work has already been done, but not enough.

#### What is missing? What do you want to see?
Indexation

#### Can you do this yourself and submit a Pull Request?
No. @benolayinka please check this, and sync with @adriansmares about it as well for help

**Comment by adriansmares** [comment]
Fixed by https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1020.
