### ISSUE TITLE
Document how to connect a Gateway to TTS using the MQTT protocol

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#1023]
#### Summary
Gateways can connect to a Gateway Server by exchanging Protocol Buffers over MQTT. MQTT is available over TLS, providing confidentiality of messages exchanged between the gateway and the network. 
- https://www.thethingsindustries.com/docs/reference/components/gateway-server/#mqtt-protocol
- https://www.thethingsindustries.com/docs/reference/api/gateway_server_mqtt/
#### Why do we need this ?
To connect Gateways to The Things Stack using MQTT Protocol.

#### What is already there? What do you see now?
Gateways connecting to The Things Stack using the LoRa Basics Station and UDP protocols. 
https://www.thethingsindustries.com/docs/gateways/concepts/

#### What is missing? What do you want to see?
Document a guide for connecting Gateways to TTS using the MQTT protocol.
#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

No.

**Comment by NicolasMrad** [comment]
closing this as we do not want to currently document such a feature
