### ISSUE TITLE
Missing search Enddevices API

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsIndustries/lorawan-stack-docs#1060]
#### Summary
The API search EndDevices is missing from the end-device section.

#### Why do we need this ?
So people can find it and use it

#### What is already there? What do you see now?
It's not in the docs, but it's already implemented

#### What is missing? What do you want to see?
The API with it's documentation

#### How do you propose to document this?
@nejraselimovic please ping @adriansmares if you require assistance here

#### Can you do this yourself and submit a Pull Request?
No

**Comment by adriansmares** [comment]
Specifically we have this service listed in a couple of places:
- Applications: https://www.thethingsindustries.com/docs/reference/api/application/#the-entityregistrysearch-service
- Clients: missing, needs to be added.
- End devices: missing, needs to be added. It is called `EndDeviceRegistrySearch` however.
- Gateways: https://www.thethingsindustries.com/docs/reference/api/gateway/#the-entityregistrysearch-service
- Organizations: https://www.thethingsindustries.com/docs/reference/api/organization/#the-entityregistrysearch-service
- Users: https://www.thethingsindustries.com/docs/reference/api/user/#the-entityregistrysearch-service
- Accounts: Does not exist, but maybe we could add an' Accounts API' section just for it.
