### ISSUE TITLE
Add docs for filter data path

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsIndustries/lorawan-stack-docs#1061]
#### Summary
"Filter Data Path" is missing from the docs, it's used for masking out parameters in a webhook.

#### Why do we need this ?
So people can know about it.

#### What is already there? What do you see now?
Not found in the docs

#### What is missing? What do you want to see?
the relative doc

#### Can you do this yourself and submit a Pull Request?
No

**Comment by nejraselimovic** [comment]
Do you maybe have a few more info about this?
