### ISSUE TITLE
Add `2-4c-mtls-s3` CloudFormation template to the AWS ECS deployment documentation

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#1064]
#### Summary

The Things Stack on AWS ECS deployment supports [mutual TLS](https://www.thethingsindustries.com/docs/getting-started/aws/ecs/mutual-tls/) authentication via a supported proxy (Envoy) from `v3.22.2`. It requires deploying `2-4c-mtls-s3` CloudFormation template which generates an S3 bucket to store CA certificates. Hence, add the `2-4c-mtls-s3` CloudFormation template to the [deployment](https://www.thethingsindustries.com/docs/getting-started/aws/ecs/deployment/) guide for deploying The Things Stack on AWS ECS.

#### Why do we need this ?

To deploy `2-4c-mtls-s3` CloudFormation template for generating an S3 bucket to store CA certificates for Mutual TLS configuration.

#### What is already there? What do you see now?

Steps for [deploying The Things Stack on AWS ECS](https://www.thethingsindustries.com/docs/getting-started/aws/ecs/deployment/) with the CloudFormation templates.

#### What is missing? What do you want to see?

Add `2-4c-mtls-s3` CloudFormation template in the [Deployment](https://www.thethingsindustries.com/docs/getting-started/aws/ecs/deployment/) section.

cc: @adriansmares 

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

No, @nejraselimovic

**Comment by adriansmares** [comment]
For the reference, the template has to be deployed _only_ if the mutual TLS functionality is to be enabled. It is not a required template otherwise, and can be skipped.
