### ISSUE TITLE
Add application and end-device NOC documentation

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsIndustries/lorawan-stack-docs#1092]
#### Summary
We need to add the application and end-device NOC documentation on top of the existing gateway NOC documentation.

#### Why do we need this ?
To document the application and end-device metrics

#### What is already there? What do you see now?
Only gateway documentation

#### What is missing? What do you want to see?
Application and end-device documentation with screenshots

#### Can you do this yourself and submit a Pull Request?
No. @benolayinka can you put this on your priority list, because the NOC is already released.

**Comment by pradeeka7** [comment]
@NicolasMrad - Now you can close this :)
