### ISSUE TITLE
Automate the documentation release process

### ISSUE THREAD

**Issue by NicolasMrad** [TheThingsIndustries/lorawan-stack-docs#1093]
#### Summary
The release process should be automated so that it's faster

#### Why do we need this ?
Automating it will making the release process faster.

#### What is already there? What do you see now?
Currently it's being done manually.

#### What is missing? What do you want to see?
To automate the whole thing

#### How do you propose to document this?
This issue has the checklist of what is usually done in a release:
https://github.com/TheThingsIndustries/lorawan-stack-docs/issues/1083

#### Can you do this yourself and submit a Pull Request?
No

**Comment by KrishnaIyer** [comment]
@happyRip: Please prioritise this issue for October. This saves us a lot of time from doing manual work.

**Comment by KrishnaIyer** [comment]
I'll pick this back up as part of the documentation work I'm working on.
