### ISSUE TITLE
Recreate the AWS deployment architecture diagram

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#110]
#### Summary
The AWS deployment architecture image in [AWS Deployment Guide](https://thethingsstack.io/getting-started/aws/ami/deployment-guide/) needs to be recreated, because it's incomprehensible, the icons are too small and connections between them are ambiguous.

#### What is already there? What do you see now?
![aws-deployment-architecture](https://user-images.githubusercontent.com/65215579/99655352-e9553c80-2a5b-11eb-9608-40b873935bb8.png)

#### What is missing? What do you want to see?
We need an improved diagram, with bigger icons and clearly visible connections.

#### Can you do this yourself and submit a Pull Request?
I think this needs to be someone who knows what this diagram represents. Maybe @johanstokking?

**Comment by johanstokking** [comment]
I agree. Reassigning to @KrishnaIyer.

[This is a good reference](https://thethingsstack.io/integrations/aws-iot/default/architecture/)
