### ISSUE TITLE
Downlink message failed with result "TOO EARLY"

### ISSUE THREAD

**Issue by ArishaValorilii** [TheThingsIndustries/lorawan-stack-docs#1105]
Class C
End device joined correctly and AS downlink messages can be scheduled correctly to end devices.
But  after some time, e.g. some hours later, I always get the error message - Downlink message failed with result "TOO EARLY".
Then I have to reset the end device and join the network, the downlink message correctly scheduled.
The error repeatedly happened everyday.  TTN told me the timestamp is too much in advance, but I don't know where to synchronize the timestamp.

**Comment by KrishnaIyer** [comment]
Please create an issue with reproduction mechanism/logs where necessary in [The Things Stack Open Source repository](https://github.com/TheThingsNetwork/lorawan-stack/issues).
