### ISSUE TITLE
Update Subscription and Billing Managements docs

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#1116]
#### Summary
There were quite some changes to Subscription and Billing Management, so docs need to reflect these changes
Refs #1107 

#### Can you do this yourself and submit a Pull Request?
Yes

**Comment by KrishnaIyer** [comment]
@nejraselimovic: Can you please pick this up in Oct?

**Comment by nejraselimovic** [comment]
> @nejraselimovic: Can you please pick this up in Oct?

Yep
