### ISSUE TITLE
Add documentation on downlink transmission failed with Collision Packet error in the device events

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#1121]
#### Summary

The `COLLISION_PACKET` error occurs if the emission of a downlink overlaps the emission of another downlink. In LoRa, frame collisions happen when two or more packets overlap in time and use the same LoRa parameters, i.e. the same spreading factor (SF), bandwidth (BW), and same frequency. In The Things Stack console device live events, we will observe the downlink failure event in the below format.
> Failed to transmit downlink          Downlink transmission failed with result `COLLISION_PACKET`

#### Why do we need this ?

To assist users in resolving the `COLLISION_PACKET` issue from their end.

#### What is already there? What do you see now?

[Troubleshooting Devices](https://www.thethingsindustries.com/docs/devices/troubleshooting/) guide with common issues and resolutions while working with end devices in The Things Stack.

#### What is missing? What do you want to see?

...

#### How do you propose to document this?

**Insights:**

- Generally, the `COLLISION_PACKET` error occurs if the device downlink overlaps the emission of another downlink which means there is already a packet programmed in the requested timeframe. In LoRa, frame collisions happen when two or more packets overlap in time and use the same LoRa parameters, i.e. the same spreading factor (SF), bandwidth (BW), and same frequency.

- Users can enable server-side buffering of downlink messages. This is recommended for gateways using the Semtech UDP Packet Forwarder v2.x or older, as it does not feature a just-in-time queue. If enabled, the Gateway Server schedules the downlink message late to the gateway so that it does not overwrite previously scheduled downlink messages that have not been transmitted yet. So, enable `schedule_downlink_late` in the Gateway console of The Things Stack and reboot/restart the physical gateway to see the change come into effect.

#### Can you do this yourself and submit a Pull Request?

No, @nejraselimovic

**Comment by KrishnaIyer** [comment]
@ymgupta: This seems like a very small item. Can you please create a PR and request my review?
