### ISSUE TITLE
Some readers think that certain pages have little or no content

### ISSUE THREAD

**Issue by pradeeka7** [TheThingsIndustries/lorawan-stack-docs#1142]
#### Summary

Some readers think that pages similar to this one (https://www.thethingsindustries.com/docs/gateways/models/) have a lack of content or no content. However, the content is actually there organized as sub-sections and accessible from the left menu.

![image](https://github.com/TheThingsIndustries/lorawan-stack-docs/assets/36432168/672e313e-34d9-485a-b307-19502c3493a3)

#### Why do we need this ?

...

#### What is already there? What do you see now?

To easily find the content of the page.

#### What is missing? What do you want to see?

Add a card for each sub-section like this. 

![image](https://github.com/TheThingsIndustries/lorawan-stack-docs/assets/36432168/579d4d8f-0ffa-415b-9c83-f2d8236a2521)

#### How do you propose to document this?

However, I understand that if a page has a large number of sub-sections, this may not be possible. Therefore, we have to think about an alternative solution (e.g. for the gateway models page, we can add 'This page contains guides with instructions for connecting popular LoRaWAN® gateways. Simply select the gateway that you want to learn about from the left menu).

#### Can you do this yourself and submit a Pull Request?

Not yet, let's finalize a solution @nejraselimovic @benolayinka

**Comment by nejraselimovic** [comment]
We already had cards there and removed it because it was too crowded. I think the easiest and best solution is to just reword this sentence and point people to look at the left menu.

**Comment by pradeeka7** [comment]
> I think the easiest and best solution is to just reword this sentence and point people to look at the left menu.

let's do it.

**Comment by KrishnaIyer** [comment]
Great @pradeeka7 can you come up with a pull request?

**Comment by pradeeka7** [comment]
@KrishnaIyer Yes, I am working on it.

**Comment by KrishnaIyer** [comment]
closed by #1151
