### ISSUE TITLE
ConnectedTimeBucket API response missing from docs (and probably others too)

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#1144]
#### Summary

While making a video about the NOC API I realized this link is broken and the response is not documented

![screenshot_2023-07-18_at_10 11 55_720](https://github.com/TheThingsIndustries/lorawan-stack-docs/assets/6963436/72fe3b6f-f419-4066-978f-e7c07523d438)

@johanstokking sent the description, is it missing from the api files or is there something that's not building?

`
// Number of entities connected in a time bucket.
message ConnectedTimeBucket {
  google.protobuf.Timestamp time = 1 [(validate.rules).timestamp.required = true];
  uint32 count = 2;
}

// Number of entities connected.
message ConnectedTimeBuckets {
  repeated ConnectedTimeBucket hourly_buckets = 1;
  repeated ConnectedTimeBucket daily_buckets = 2;
  repeated ConnectedTimeBucket weekly_buckets = 3;
}
`
In general our API docs are pretty clunky and we should probably consider refactoring how we build/present them.

**Comment by johanstokking** [comment]
@benolayinka you can insert the missing message(s) on the page, see https://github.com/TheThingsIndustries/lorawan-stack-docs/blob/master/doc/content/reference/api/network_operations_center.md. Please check any other missing messages if any, other than these two.

**Comment by nejraselimovic** [comment]
I'll close this issue since missing messages have been added in https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1185 and https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1201. If we see something missing we can open another issue, and for refactoring as well.
