### ISSUE TITLE
Minor additions to API Usage Troubleshooting documentation

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#1155]
#### Summary

Add the below commonly occurring errors to **API Usage Troubleshooting** documentation while using The Things Stack APIs.  

  - `no_application_rights`
  - `api_key_not_found`
  - `unauthenticated`
  - `curl: (3) URL using bad/illegal format or missing URL`

#### Why do we need this ?

To assist users in resolving API issues by referring to the API Usage Troubleshooting guide.

#### What is already there? What do you see now?

[API Usage Troubleshooting](https://www.thethingsindustries.com/docs/the-things-stack/interact/api/#api-usage-troubleshooting)

#### What is missing? What do you want to see?

Add the below errors and resolutions in the [API Usage Troubleshooting](https://www.thethingsindustries.com/docs/the-things-stack/interact/api/#api-usage-troubleshooting) document.

  - `no_application_rights`
  - `api_key_not_found`
  - `unauthenticated`
  - `curl: (3) URL using bad/illegal format or missing URL`

#### How do you propose to document this?

1. Error `no_application_rights`

**Description:** This error occurs when the API request is made to an entity with an API Key that doesn't have the required rights to access or modify resources related to a specific application. Also, if the `Bearer` keyword is missing before the API Key in the Authorization header of the cURL command, the error occurs.

**Resolution:** To resolve this issue, ensure the API Key configured in the API Call has the necessary rights to interact with the target application. And also ensure the `Bearer` keyword is present before the API Key in the cURL command. 

-----

2. Error `api_key_not_found`

**Description:** This error indicates that the specified API key in the request headers or parameters is not valid or doesn't exist.

**Resolution:** To resolve this issue, double-check the API key provided in the API Call request and ensure that it is correct and still valid. If the API key has expired or been revoked, generate a new API key and update the API Call request with the new key.   

----

3. Error `unauthenticated`

**Description:** This error occurs when the API request is made without proper authentication credentials.

**Resolution:** To resolve this issue, ensure to include the correct API key in the authentication request header. 

---

4. Error `curl: (3) URL using bad/illegal format or missing URL`

**Description:** This error is related to the cURL command used to make API requests. It suggests that the URL format in the cURL command is incorrect or missing.

**Resolution:** To resolve this issue, verify the cURL command used for the API request. Double-check the URL syntax to ensure it is correct and complete. If this error occurs when using cURL, ensure that the specified endpoint is properly configured and included all necessary parameters.

#### Can you do this yourself and submit a Pull Request?

No, @nejraselimovic

**Comment by KrishnaIyer** [comment]
Refs: https://github.com/TheThingsIndustries/product-management/issues/23
