### ISSUE TITLE
Add the scenario `unable to view the end device live events` in The Things Stack console

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#1189]
#### Summary

Generally, The Things Stack Console fetches the device live stream events from the Application Server, which is exposed on `8883` over the MQTT protocol. If there are any issues with port `8883` on the PC, there might be a chance to be unable to view the end device live events in the Console. Please consider adding this scenario and its corresponding resolution steps to the [Console troubleshooting guide](https://www.thethingsindustries.com/docs/the-things-stack/interact/console/troubleshooting/)."

#### Why do we need this ?

To assist The Things Stack users in troubleshooting issues with device live data in the TTS Console.

#### What is already there? What do you see now?

[Troubleshooting Console
](https://www.thethingsindustries.com/docs/the-things-stack/interact/console/troubleshooting/)
#### What is missing? What do you want to see?

Add the cause and resolution to the issue ` end device live events are not visible in the console`. 

#### How do you propose to document this?

**Insights:** 

- Generally, The Things Stack Console fetches the live stream events from the Application Server data/events, which are exposed on 8883 over the MQTT protocol. So, there shouldn't be any issues related to port `8883` on the user's PC. 
- Also, sometimes the issue could be specific to the OS and browser versions of the user's PC. In such cases, users need to test the behavior with the other PCs to isolate the issue of their specific PC.

#### Can you do this yourself and submit a Pull Request?

No, @nejraselimovic

**Comment by KrishnaIyer** [comment]
> The Things Stack Console fetches the live stream events from the Application Server data/events, which are exposed on 8883 over the MQTT protocol. So, there shouldn't be any issues related to port 8883 on the user's PC.

I don't think so. Events are streamed on the `/api/v3/events` HTTP route. If there are issues with the Console handling event streams, we are working on a redesign of how the console receives events to improve the performance.

cc: @adriansmares/ @kschiffer

**Comment by nejraselimovic** [comment]
> > The Things Stack Console fetches the live stream events from the Application Server data/events, which are exposed on 8883 over the MQTT protocol. So, there shouldn't be any issues related to port 8883 on the user's PC.
> 
> I don't think so. Events are streamed on the `/api/v3/events` HTTP route. If there are issues with the Console handling event streams, we are working on a redesign of how the console receives events to improve the performance.
> 
> cc: @adriansmares/ @kschiffer

Considering this, can we close this issue then?

**Comment by KrishnaIyer** [comment]
Let's close this issue indeed. If this happens again, @ymgupta please create a bug request.
