### ISSUE TITLE
Missing API response for Webhook Downlink Scheduling

### ISSUE THREAD

**Issue by cwkhawand** [TheThingsIndustries/lorawan-stack-docs#1209]
#### Summary
Currently when POSTing to the Webhook Downlink API, the API response is empty.

...

#### Why do we need this ?
Ideally, the API should at least return the unique identifier of the downlink to be able to track it later when it is confirmed for example.

...

#### What is missing? What do you want to see?
Ideally the API should return the whole Downlink object data.
...

**Comment by nejraselimovic** [comment]
Hi, I think this issue should be closed here and submitted to [stack repository](https://github.com/TheThingsNetwork/lorawan-stack)
