### ISSUE TITLE
Document using ttn-lw-migrate for device migrations from The Things Network Stack V2

### ISSUE THREAD

**Issue by neoaggelos** [TheThingsIndustries/lorawan-stack-docs#121]
#### Summary

Document using `ttn-lw-migrate` for migrating devices from The Things Network Stack V2

#### Why do we need this ?

Stop depending on `ttnctl`. `ttn-lw-migrate` is easier to maintain and update, uses the TTS V3 APIs instead of custom structs, and can properly export session frame counters.

#### What is already there? What do you see now?

Documentation for using `ttnctl` to export devices.

#### What is missing? What do you want to see?

Documentation for using `ttn-lw-migrate` instead.

#### How do you propose to document this?

Remove or deprecate existing steps, add instructions for `ttn-lw-migrate`. I have started some work in https://github.com/TheThingsIndustries/lorawan-stack-docs/tree/doc/ttn-lw-migrate.

#### Can you do this yourself and submit a Pull Request?

I have written down the steps required for using `ttn-lw-migrate`, assigning @benolayinka for the rest and adding to Next Up. Re-assign as needed. Can also help with answering questions and testing.

**Comment by benolayinka** [comment]
Closed by https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/130
