### ISSUE TITLE
Go maps package used requiring go v1.21 or later

### ISSUE THREAD

**Issue by jhanmann** [TheThingsIndustries/lorawan-stack-docs#1244]
The DEVELOPMENT.md file indicates that go v1.18.x is supported (refer to line 58) but since the maps package is only in Go v1.21 or later this is not correct I believe. When I tried to build with Go 1.91.1 it failed due to the missing maps package in the go src directory.

It appears the change from the experimental maps package to the now officially released maps package was done within the last few months but this point in the documentation was not updated it appears.

Minor error and fairly easy to sort out but reporting it for you regardless.

**Comment by nejraselimovic** [comment]
Closing this as it has been covered in another PR
