### ISSUE TITLE
Document Billing and Subscription information

### ISSUE THREAD

**Issue by KrishnaIyer** [TheThingsIndustries/lorawan-stack-docs#1255]
#### Summary

Refs https://github.com/TheThingsIndustries/lorawan-stack-support/issues/958

#### Why do we need this ?

To help users better understand TTSC subscription and billing flows.

#### What is already there? What do you see now?

https://www.thethingsindustries.com/docs/the-things-stack/cloud/billing-and-subscription-management/#manage-your-subscriptions-support-and-billing-plans

#### What is missing? What do you want to see?

Update content from the discussion in https://github.com/TheThingsIndustries/lorawan-stack-support/issues/958

#### How do you propose to document this?

Updating the content in the relevant pages.

#### Can you do this yourself and submit a Pull Request?

Can review.

**Comment by nejraselimovic** [comment]
Closing this as it was covered by https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1190
