### ISSUE TITLE
Add new metadata to gateways.

### ISSUE THREAD

**Issue by LDannijs** [TheThingsIndustries/lorawan-stack-docs#1259]
#### Summary

Add some metadata to the gateway docs for use in the Partner Portal per requested by @benolayinka 

#### Why do we need this ?

To make it easier to add the info of a gateway to the Partner Portal.

#### What is already there? What do you see now?

Basic metadatam like title, description

#### What is missing? What do you want to see?

More metadata like vendor, ip rating, backhaul, etc.

#### How do you propose to document this?

It's all frontmatter, so documentation isn't necessary.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by KrishnaIyer** [comment]
@LDannijs: Please fill out the issue template properly.

**Comment by nejraselimovic** [comment]
Closing this since the referenced PR is merged
