### ISSUE TITLE
Rate limiting Redis backend

### ISSUE THREAD

**Issue by happyRip** [TheThingsIndustries/lorawan-stack-docs#1273]
#### Summary

Document new configuration options of rate limiting provider.

#### Why do we need this ?

After finishing the work on https://github.com/TheThingsIndustries/lorawan-stack/issues/2969 we need to document the new features.

#### What is already there? What do you see now?

Rate limiting docs.

#### What is missing? What do you want to see?

Redis rate limiting docs.

#### How do you propose to document this?

Add missing docs.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by KrishnaIyer** [comment]
@happyRip: Can you please add this documentation for the new release?
