### ISSUE TITLE
Minor changes to the API documentation

### ISSUE THREAD

**Issue by Siva-7482** [TheThingsIndustries/lorawan-stack-docs#1301]
#### Summary

We have identified minor improvements in The Things Stack API documentation. 

1. Update the length of token-id and token-secret. 
2. Update the typo of the word perform. 
3. Update the URL references of **messages.proto** and **lorawan.proto**.
4. Update The Things Stack Community Edition as The Things Stack Sandbox. 

#### Why do we need this ?

To ensure the API documentation is up to date.

#### What is already there? What do you see now?

[The Things Stack API documentation](https://www.thethingsindustries.com/docs/api/)

#### What is missing? What do you want to see?

Update the API documentation for the recommended sections. 

#### How do you propose to document this?

**1. Update the length of `token-id`, and `token-secret`:** 

In the 'What are API Keys?' section, it is noted that there is a discrepancy in the length of the API Keys.![image](https://github.com/CyberEyeResearchLabs/TTI-Support/assets/105837895/34f8f6ff-ca58-4cff-8539-fe43df3484bf)

The `token-id` length is mentioned as 24 characters, but it seems 39 characters long. Similarly, the `token-secret` length is mentioned as 32 characters, whereas it seems 52 characters in length.

---

**2. Update the typo of the word perform:**

The Authorization section contains a typo; `perfrom` should be corrected to `perform`. Please find the section here: [Authorization Section](https://www.thethingsindustries.com/docs/api/concepts/auth/#authorization)

<img width="514" alt="image" src="https://github.com/CyberEyeResearchLabs/TTI-Support/assets/105837818/6e4744bb-992b-4c29-881d-66ef66605e71">

---

**3. Update the URL references of **messages.proto** and **lorawan.proto**:**

The URLs for `messages.proto` and `lorawan.proto` are broken, resulting in a `404 Not Found` error when accessed. Please update the **messages.proto** and **lorawan.proto** with the correct URLs.  Ref: [LoRa Gateway MQTT](https://www.thethingsindustries.com/docs/api/concepts/lora-gateway/#mqtt)

![image](https://github.com/CyberEyeResearchLabs/TTI-Support/assets/105837895/2335c551-c787-4aca-a309-dabd4bb8d750)

---

**4. Update The Things Stack Community Edition as The Things Stack Sandbox:** 

In the errors section of the API documentation, we need to update `The Things Stack Community Edition` with `The Things Stack Sandbox`. Please find the reference here: [Troubleshooting](https://www.thethingsindustries.com/docs/api/concepts/troubleshooting/#listing-gateways-via-api-call-works-for-the-eu1-the-things-stack-cloud-cluster-but-wont-work-for-the-nam1-cluster)

![image](https://github.com/CyberEyeResearchLabs/TTI-Support/assets/105837895/ab516b9e-79e9-471f-b881-7922f76e2e19)

#### Can you do this yourself and submit a Pull Request?

We do not have the references for the `messages.proto` and `lorawan.proto`. Hence, filed this issue instead of PR.

No, @nejraselimovic

**Comment by KrishnaIyer** [comment]
Covered in https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1308/
Next time @Siva-7482 please create a PR since you have all the required information.
