### ISSUE TITLE
Azure Kubernetes upgrade process note

### ISSUE THREAD

**Issue by happyRip** [TheThingsIndustries/lorawan-stack-docs#1307]
#### Summary

https://github.com/TheThingsIndustries/lorawan-stack-k8s-infra/pull/20#pullrequestreview-1878186625

#### Why do we need this ?

To inform users about the upgrade procedure of the Kubernetes version in AKS.

#### What is already there? What do you see now?

We have Azure deployment docs.

#### What is missing? What do you want to see?

No mention of the upgrade procedure.

#### How do you propose to document this?

Add a note informing users of the procedure.

#### Can you do this yourself and submit a Pull Request?

Yes.

**Comment by KrishnaIyer** [comment]
Closed via https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1339
