### ISSUE TITLE
Document connecting the Dragino LPS8 gateway in LoRa Basics Station mode to The Things Stack

### ISSUE THREAD

**Issue by peetharavi** [TheThingsIndustries/lorawan-stack-docs#1332]
#### Summary

We can connect Dragino LPS8 Gateway to The Things Stack using UDP and LoRa Basics Station modes. However, we don't have a documentation guide for connecting the Dragino LPS8 gateway in LoRa Basics Station mode to TTS.

#### Why do we need this?

To assist users in connecting the Dragino LPS8 Gateway to The Things Stack using LoRa Basics Station. 

#### What is already there? What do you see now?

[Connecting Dragino LPS8 to TTS in UDP mode](https://www.thethingsindustries.com/docs/gateways/models/dragino-lps8/)

#### What is missing? What do you want to see?

Document how to connect the Dragino LPS8 Gateway to The Things Stack using the LoRa Basics Station mode.

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

No. @nejraselimovic.

**Comment by nejraselimovic** [comment]
@LDannijs any way you can get your hands on this gateway and write a doc?

**Comment by LDannijs** [comment]
Sure!
