### ISSUE TITLE
Update Kubernetes deployment documentation

### ISSUE THREAD

**Issue by happyRip** [TheThingsIndustries/lorawan-stack-docs#1335]
#### Summary

Ref https://github.com/TheThingsIndustries/lorawan-stack-k8s/pull/37
Ref https://github.com/TheThingsIndustries/lorawan-stack-k8s-infra/pull/22

#### Why do we need this ?

After merging these PRs the docs need to be updated to reflect the changes made to the templates.

#### What is already there? What do you see now?

There are Kubernetes and Azure managed deployment docs.

#### What is missing? What do you want to see?

Document new changes.

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by KrishnaIyer** [comment]
done via https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1339
