### ISSUE TITLE
Misaligned/invisible distributions element

### ISSUE THREAD

**Issue by LDannijs** [TheThingsIndustries/lorawan-stack-docs#1380]
#### Summary

The element that shows what distributions of The Things Stack are supported seems to be hidden and misaligned.  

https://github.com/user-attachments/assets/7476783f-17b4-4b4f-9719-0a7398b37cc7

#### Why do we need this ?

This needs to be fixed to properly show it.

#### What is already there? What do you see now?

The TTS distributions element is misaligned and appears invisible. The region of where it shows is also too large it seems.

#### What is missing? What do you want to see?

...

#### How do you propose to document this?

The dependencies got updated few days ago so i believe something went wrong with the update.

#### Can you do this yourself and submit a Pull Request?

Probably not, @johanstokking

**Comment by KrishnaIyer** [comment]
We need to clean up this entire system of differentiating tiers/deployment models anyway.
@pierrephz: Let's work on some UX for this.

**Comment by pierrephz** [comment]
### Here is a rework of the tags:

<img width="1945" alt="Screenshot 2024-10-23 at 14 27 42" src="https://github.com/user-attachments/assets/6ede1148-171d-4139-aee8-e42bb1e8f866">

### Example of the tags in use:

![docs-tags](https://github.com/user-attachments/assets/02945ddf-5be5-4f15-8bef-aaae1321a6c1)

**Comment by ryaplots** [comment]
@KrishnaIyer There is also a "dedicated cloud" badge, what is this? Is this equivalent to enterprise or to cloud plus? Or do we not support this anymore?

**Comment by KrishnaIyer** [comment]
Good question. We indeed don't use that anymore, you can remove references to those 👍

**Comment by KrishnaIyer** [comment]
This is done via #1387 and deployed.
