### ISSUE TITLE
Inline shortcodes in section headers break anchor links

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#139]
#### Summary

Adding shortcodes to section headers changes the section id and therefore breaks anchor links

<img width="475" alt="Screenshot 2020-12-02 at 16 18 29" src="https://user-images.githubusercontent.com/6963436/100893063-3e14a080-34bb-11eb-9979-56b047605035.png">
<img width="971" alt="Screenshot 2020-12-02 at 16 17 35" src="https://user-images.githubusercontent.com/6963436/100893071-410f9100-34bb-11eb-8c6d-b64582931521.png">

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by benolayinka** [comment]
Solutions I see are to

- Do something clever to filter shortcodes when generating the id slug
- Wrap the header in a shortcode
- Move the shortcode to another line

@htdvisser what do you think?

**Comment by htdvisser** [comment]
I think the "Cloud and Enterprise Only" stuff could be moved to a different line. I think we already had an idea about using "tags" to indicate applicable distributions, then we can just as well add some CSS to make them float on the right of the section.

Another option would be to wrap the entire section with a shortcode, then we can even add a nice colored line on the right to visualize where that "Cloud and Enterprise Only" part ends.
