### ISSUE TITLE
Create docs banner for migration to tti.com/docs

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#150]
#### Summary

Documentation is moving to tti.com/docs, so let's put a notification at the top of the page, so that people know why they were redirected.

@pierrephz can you design something simple? I think something basic at the top of the page, like https://www.hongkiat.com/blog/show-n-hide-notification-bar/

**Comment by pierrephz** [comment]
![image](https://user-images.githubusercontent.com/26456318/101502473-47958100-3971-11eb-9c50-50f1340154e6.png)

**Comment by benolayinka** [comment]
Closed by #153
