### ISSUE TITLE
Multiple docs with same title breaks search

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#160]
#### Summary

Every cloud integration has a section called creating webhooks, and this confuses search. IDEM with MQTT

Possible solutions
- Rename the sections to include the parent section name (i.e creating a webhook for Akenza)
- Linking to one generic section

<img width="846" alt="Screenshot 2020-12-15 at 13 50 22" src="https://user-images.githubusercontent.com/6963436/102217507-f5a6ab00-3edc-11eb-81de-ed868ac70b8f.png">

#### Can you do this yourself and submit a Pull Request?

@nejraselimovic putting you in charge

**Comment by ajovertoom** [comment]
Also beyond the integrations, this applies to Basic Station, see scrshot. And there are probably more generic concepts with multiple bespoke implementations.
![Schermafbeelding 2020-12-16 om 11 34 17](https://user-images.githubusercontent.com/24291422/102337404-b6d32c80-3f92-11eb-9bfa-93d87d0b5f73.png)

**Comment by nejraselimovic** [comment]
I would go for renaming the sections

**Comment by nejraselimovic** [comment]
I'm not sure how to approach this. I was thinking that the most easy way was to just rename the sections, but look at the following example. 

![Screenshot from 2020-12-16 13-28-18](https://user-images.githubusercontent.com/65215579/102348754-9dd27780-3fa2-11eb-871b-227c4d7c3302.png)

If you look at the last part **Migrating to The Things Stack**, clicking the first result leads [here](https://thethingsindustries.com/docs/getting-started/migrating/) which is fine, but the second results leads [here](https://thethingsindustries.com/docs/getting-started/migrating/configure-mac-settings/) which is not fine, and as far as I can see the problem there isn't the section name. I don't have a clue how this search works, so I'm not sure if renaming sections would resolve this issue entirely.

**Comment by benolayinka** [comment]
> I'm not sure how to approach this. I was thinking that the most easy way was to just rename the sections, but look at the following example.
> 
> ![Screenshot from 2020-12-16 13-28-18](https://user-images.githubusercontent.com/65215579/102348754-9dd27780-3fa2-11eb-871b-227c4d7c3302.png)
> 
> If you look at the last part **Migrating to The Things Stack**, clicking the first result leads [here](https://thethingsindustries.com/docs/getting-started/migrating/) which is fine, but the second results leads [here](https://thethingsindustries.com/docs/getting-started/migrating/configure-mac-settings/) which is not fine, and as far as I can see the problem there isn't the section name. I don't have a clue how this search works, so I'm not sure if renaming sections would resolve this issue entirely.

Renaming the sections is a good start, let's do what we can to fix that. The Migrating issue is weird, I'll message Algolia about it.

**Comment by nejraselimovic** [comment]
> > I'm not sure how to approach this. I was thinking that the most easy way was to just rename the sections, but look at the following example.
> > ![Screenshot from 2020-12-16 13-28-18](https://user-images.githubusercontent.com/65215579/102348754-9dd27780-3fa2-11eb-871b-227c4d7c3302.png)
> > If you look at the last part **Migrating to The Things Stack**, clicking the first result leads [here](https://thethingsindustries.com/docs/getting-started/migrating/) which is fine, but the second results leads [here](https://thethingsindustries.com/docs/getting-started/migrating/configure-mac-settings/) which is not fine, and as far as I can see the problem there isn't the section name. I don't have a clue how this search works, so I'm not sure if renaming sections would resolve this issue entirely.
> 
> Renaming the sections is a good start, let's do what we can to fix that. The Migrating issue is weird, I'll message Algolia about it.

Deal, I'm on it tommorow
