### ISSUE TITLE
Align text across page cards

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#207]
#### Summary
@benolayinka Should we define a fixed top margin (or however it's being done) for page cards? The text is not aligned when the title in one card is in one row, and in two rows in the other.

![Screen Shot 2021-01-19 at 15 35 53](https://user-images.githubusercontent.com/65215579/105050860-7e7dad00-5a6e-11eb-9684-76989bd90a0f.png)

**Comment by benolayinka** [comment]
I think we leave this as is, creating a fixed margin would also break if a title were then three rows, for example
