### ISSUE TITLE
Title anchor with "new in version" tag not rendering correctly inside tabs

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#218]
#### Summary
When a title is inside tabs, the anchor doesn't render correctly if there's also a `new  in version` tag.

#### What is already there? What do you see now?

Example: **Download configuration in the Console** title here -> https://www.thethingsindustries.com/docs/gateways/semtech-udp-packet-forwarder/

![Screenshot from 2021-02-04 10-51-07](https://user-images.githubusercontent.com/65215579/106890911-491dc400-66ea-11eb-92fa-fdb68f4c7bb5.png)

![Screenshot from 2021-02-04 10-51-20](https://user-images.githubusercontent.com/65215579/106890909-48852d80-66ea-11eb-9d40-735d017f26a6.png)

#### What is missing? What do you want to see?
Works well if outside of tabs.

**Comment by nejraselimovic** [comment]
Another thing relatable to using tabs -> right hand navigation not working on this page

![Screenshot from 2021-03-24 10-00-22](https://user-images.githubusercontent.com/65215579/112282977-ee373080-8c87-11eb-8757-3a7732bcb491.png)

**Comment by benolayinka** [comment]
Closed by a commit I can't find, but https://github.com/TheThingsIndustries/lorawan-stack-docs/commit/221d181de7bfac8dee2c0d9f61f49be595a166c5#diff-5ade1e9814fd2258512c15aa51eed853ec0c7d4e3f791aa507eea381917ac39a
