### ISSUE TITLE
Search feature is broken

### ISSUE THREAD

**Issue by rish-c** [TheThingsIndustries/lorawan-stack-docs#240]
#### Summary
Search function on the docs is broken (and has been for over a month now)

#### Why do we need this ?
Easier navigation 

#### What is already there? What do you see now?
The search function used to work but I think since 3.10 it is broken

#### What is missing? What do you want to see?
The search field is there but it doesn't work properly. 
Maybe if this 3rd party search add on isn't good, we can look for an alternate option.

#### Can you do this yourself and submit a Pull Request?
@benolayinka @nejraselimovic

**Comment by rish-c** [comment]
Can someone assign and add the labels etc. I dont have rights to do so.

**Comment by benolayinka** [comment]
I've been emailing them for a month. Will keep trying, Algolia is the best and most popular option
