### ISSUE TITLE
Update our font

### ISSUE THREAD

**Issue by pierrephz** [TheThingsIndustries/lorawan-stack-docs#252]
#### Summary

Change `Lato` into `Inter` font on the Documentation

#### Why do we need this ?

Lato is part of our old branding

#### What is missing? What do you want to see?

Here is the font: [Inter.zip](https://github.com/TheThingsIndustries/lorawan-stack-docs/files/6084076/Inter.zip)

#### Can you do this yourself and submit a Pull Request?

@benolayinka could you take this up?

**Comment by benolayinka** [comment]
Is it this? We can load from google instead -> https://fonts.google.com/specimen/Inter?preview.text_type=custom

**Comment by pierrephz** [comment]
Yes, indeed, we can do that
