### ISSUE TITLE
Clarify MQTT tenant-id usage for TTN V3

### ISSUE THREAD

**Issue by mtxgithub** [TheThingsIndustries/lorawan-stack-docs#280]
#### Summary

The Documentation for MQTT can be misleading about required tenant-id usage for TTN V3.
Adding some info can clarify it.

#### Why do we need this ?

Easier to understand on first usage; background in the Forum:
https://www.thethingsnetwork.org/forum/t/downlink-formatter/45359/8

#### What is already there? What do you see now?

https://www.thethingsindustries.com/docs/integrations/mqtt/

### MQTT Server -> "Multi-Tenancy"
_"Note that on multi-tenant environments such as Cloud, application IDs and other endpoints include the tenant ID, e.g app1@tenant1. On single tenant environments such as Open Source, the tenant ID can be removed, i.e app1."_

"tenant ID can be removed" is misleading if you read this for the first time, better add something like:
"The Things Network V3" requires including the tenant ID "@ttn"

### "Integration with MQTT Clients":

_"Eclipse Mosquitto":_
   
   (typo: replace /up by /push): in the example
mosquitto_pub -h "thethings. ...   -t "v3/app1/devices/dev1/up"  ....
(better mention the requirement of the tenant ID as well)

_"Eclipse Paho":_

Adopted the example / working would be this one (...adding the tenant-id again):

publish.single("v3/{application-id}@{tenant-id}/devices/{device-id}/down/push", '{"downlinks":[{"f_port": 15,"frm_payload":"vu8=","priority": "NORMAL"}]}', hostname="thethings.example.com", port=1883, auth={'username':"{application-id}@{tenant-id}",'password':"NNSXS.VEEBURF3KR77ZR.."})

#### How do you propose to document this?

mentioned above.

#### Can you do this yourself and submit a Pull Request?

no

**Comment by nejraselimovic** [comment]
Thank you for your contribution @mtxgithub!
