### ISSUE TITLE
Not possible to navigate to tabbed sections in right hand navigation panel

### ISSUE THREAD

**Issue by kschiffer** [TheThingsIndustries/lorawan-stack-docs#286]
#### Summary
In content pages that use descriptions for both Console and CLI, the right hand navigation will show also show the tabbed sections. However, it is not possible to navigate to tabbed content.

https://www.thethingsindustries.com/docs/gateways/adding-gateways/#adding-gateways-using-the-cli

Try clicking on `Adding Gateways using the CLI` on the right hand navigation panel. You'll see that it does nothing.

#### What is missing? What do you want to see?
If an anchor link is selected that is hidden behind a tab, the tab should activate automatically and the page should scroll to the respective section.

#### Can you do this yourself and submit a Pull Request?
@benolayinka

**Comment by benolayinka** [comment]
I don't have a good idea how to solve this. The right hand links are generated by scraping the DOM for headers, and I could add some code there but I'd like to avoid random dependency in the sidebar snippet. Maybe something like a listener when the url changes? @kschiffer ?
