### ISSUE TITLE
Using distribution shortcode with a subsection title makes it disappear from right-hand navigation bar

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#325]
#### Summary
Storage Integration Options subsection with marked distributions missing in the right-hand navigation:
![Screen Shot 2021-04-29 at 16 22 18](https://user-images.githubusercontent.com/65215579/116420296-265d0080-a83e-11eb-9112-f3cfad6e9e2a.png)

Storage Integration Options subsection appears in the right-hand navigation when distributions shortcode gets removed:
![Screen Shot 2021-04-29 at 16 22 31](https://user-images.githubusercontent.com/65215579/116420328-2ceb7800-a83e-11eb-886d-0d42e004ad11.png)

**Comment by benolayinka** [comment]
Having shortcodes inline with headings is causing us quite a few problems. It messes up anchor links, and needs some manual fixes to work. In Hugo documentation, they move the shortcodes to the text below the heading, which would look like this for us:

<img width="570" alt="Bildschirmfoto 2021-06-07 um 16 53 27" src="https://user-images.githubusercontent.com/6963436/121039026-07dd1400-c7b1-11eb-83e3-08320192e211.png">

This is a really easy fix and my preference. The other option is to wrap entire sections in some kind of background or indicator, like

<img width="665" alt="Bildschirmfoto 2021-06-07 um 16 58 51" src="https://user-images.githubusercontent.com/6963436/121039743-a5d0de80-c7b1-11eb-96bb-5fee3ef4a495.png">

**Comment by nejraselimovic** [comment]
The first option seems better indeed
