### ISSUE TITLE
Check and correct typo in nasysoutdoorgateway

### ISSUE THREAD

**Issue by felixheins** [TheThingsIndustries/lorawan-stack-docs#336]
#### Summary

Customer claims typo in /gateways/nasysoutdoorgateway/
...

#### Why do we need this ?

...

#### What is already there? What do you see now?

$ systemctl restart nas_lgw
...

#### What is missing? What do you want to see?

$ systemctl restart nas-lgw
...

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

@benolayinka could you double check this and let me know if this is the proper process for such cases in the future?

...

**Comment by benolayinka** [comment]
@felixheins perfect, thanks.
