### ISSUE TITLE
Update the `JSON File Reference` in `Migrating to The Things Stack` documentation

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#358]
#### Summary
The  **JSON File Reference** section in the **Migrating to The Things Stack** documentation is not up to date concerning the `3.12.0` API changes.

#### Why do we need this ?
If users try to add their devices by following the JSON File Reference, they will encounter issues.

#### What is already there? What do you see now?
In the current documentation, the fields are based on the older version of APIs.
For example, the field for Rx1Delay is mentioned as `mac_settings.rx1_delay.value`.  

#### What is missing? What do you want to see?
Updating the documentation with the latest API changes in the `TTS v3.12.0` version.
I.e., the field for **Rx1Delay** should be `mac_settings.rx1_delay` as per the latest API changes.

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by benolayinka** [comment]
@neoaggelos @laurensslats do you know where to find these API values?

**Comment by neoaggelos** [comment]
I can pick this up.
