### ISSUE TITLE
Sub-section delimiters to make documentation easier to track

### ISSUE THREAD

**Issue by descartes** [TheThingsIndustries/lorawan-stack-docs#371]
#### Summary
The design is nice but ruled lines between the details of a command or message but not bolder & blacker line between actual items makes finding information a blur

#### Why do we need this ?
Some of our eye balls are 50+ years old, I use three pairs of glasses now and if I'm scrolling up & down I often miss the detail I'm looking for. And as most of the migration work at present is not revenue generating, my time is a little precious to have to fight with the design.

#### What is already there? What do you see now?
<img width="959" alt="Screenshot 2021-05-30 at 11 08 52" src="https://user-images.githubusercontent.com/368323/120100377-6f9fb900-c138-11eb-9887-9034933528f5.png">

<img width="854" alt="Screenshot 2021-05-30 at 11 09 09" src="https://user-images.githubusercontent.com/368323/120100384-76c6c700-c138-11eb-99ff-04cc17010d73.png">

#### What is missing? What do you want to see?
<img width="959" alt="Screenshot 2021-05-30 at 11 08 52" src="https://user-images.githubusercontent.com/368323/120100447-b1c8fa80-c138-11eb-93c6-c0972f58eea5.png">

<img width="854" alt="Screenshot 2021-05-30 at 11 09 09" src="https://user-images.githubusercontent.com/368323/120100456-b5f51800-c138-11eb-8aae-e5e224060fce.png">

#### Can you do this yourself and submit a Pull Request?
Possibly - if only as I find Hugo interesting for my own use and also so I can recycle the content in to something as horrible as this: http://descartes.co.uk/TTSv3CLI.html which I will probably do anyway as a drill down allows people to see the big picture and then get in to the detail they need.

**Comment by descartes** [comment]
Actually, now I look at it, please consider dropping the line between the details - and perhaps right align the left hand column.

**Comment by benolayinka** [comment]
Fixed in #385 - take a look @descartes and let me know if it looks okay
