### ISSUE TITLE
Update the AWS IoT integration documentation with recent changes

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#378]
#### Summary
Update the AWS IoT integration documentation based on the recent changes in the `v3.13.0` release related to skipping payload crypto.

#### Why do we need this ?
In the recent release `v3.13.0`, we restrict scheduling downlinks from the TTS Console when the **End-to-End Encryption** (in `AWS Integration`)/**Skip Payload Crypto** (in `TTS`) is enabled. In this case, the downlinks are expected to be scheduled from AWS only and not the TTSC Console. The users are unaware of the reason for this behavior.

#### What is already there? What do you see now?
Information on **End-to-End Encryption** stating only about the encryption and decryption of application payload is not done at TTS end when this option is enabled.
Ref: https://www.thethingsindustries.com/docs/integrations/aws-iot/default/architecture/#end-to-end-encryption

#### What is missing? What do you want to see?
When the **End-to-End Encryption** option in the **AWS Integration** is `enabled`, the **Skip Payload Crypto** option in **TTS** at the application level will be `enabled`. The users are unaware of this behavior and confused on why they couldn't schedule downlinks from TTS.

Also, specify that when **End-to-End Encryption** is enabled in the AWS IoT integration, **the downlinks are not expected to be scheduled from the TTSC Console**.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/437#issuecomment-848020927

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by johanstokking** [comment]
@nejraselimovic the suggestion by @i3mSuperMan is accurate; it only needs a clarification under **End-to-end encryption**.
