### ISSUE TITLE
Mention "lbs_lns_secret" should be base64 encoded

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#399]
#### Summary
Add to description of `lbs_lns_secret` that it should be `base64` encoded.  Ref:https://www.thethingsindustries.com/docs/reference/api/gateway/#message:Gateway
#### Why do we need this?
Mention appropriate usage in docs
#### What is already there? What do you see now?
Information on what is `lbs_lns_secret`
#### What is missing? What do you want to see?
Information on encoding format/type of the secret
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by benolayinka** [comment]
Closed for https://github.com/TheThingsIndustries/lorawan-stack/issues/2717
