### ISSUE TITLE
Add a prerequisites section to the Multitech Conduit AEP gateways doc for supporting LBS

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#401]
#### Summary
Updating the current documentation with a prerequisites section to the Multitech Conduit AEP Gateway with the LoRa Basics Station configuration guide.
Ref: https://www.thethingsindustries.com/docs/gateways/multitechconduit/

#### Why do we need this?
To know which `Hardware Versions` and `Firmware Versions` supports the LoRa Basics Station functionality.

#### What is already there? What do you see now?
https://www.thethingsindustries.com/docs/gateways/multitechconduit/

#### What is missing? What do you want to see?
The current documentation does not have the prerequisites information to support the `LBS` for the Multitech Conduit gateways.

#### How do you propose to document this?
Adding the prerequisites information in the current docs according to the Multitech reference. http://www.multitech.net/developer/software/lora/running-basic-station-on-conduit/

#### Can you do this yourself and submit a Pull Request?
Yes.

**Comment by nejraselimovic** [comment]
@i3mSuperMan great to see you're doing this, please assign me and @benolayinka for review
