### ISSUE TITLE
Document differences in TTI stack level implementation of LBS protocol with reference to LBS standard.

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#409]
#### Summary
As per https://github.com/TheThingsIndustries/lorawan-stack-support/issues/451, TTS implements gateway scheduler different from LBS scheduler for good reasons. It is better to document it.
#### Why do we need this?
Document the differences and make sure gateway manufacturers know about these differences.
#### What is already there? What do you see now?
...
#### What is missing? What do you want to see?
Differences in TTI stack level implementation of LBS protocol with reference to LBS standard
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No. @benolayinka 

cc: @KrishnaIyer

**Comment by benolayinka** [comment]
i read the thread and my best understanding is that TTS modifies `xtime` to account for `RX1Delay`. Is that right? Is that all I need to document? What information could that provide for gateway manufacturers (maybe that will help me figure out where to put it in the docs)

@KrishnaIyer

**Comment by KrishnaIyer** [comment]
I'll take this one.
