### ISSUE TITLE
Document a guide for AWS SaaS deployment configuration.

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#430]
#### Summary
Document the instructions for deploying The Things Stack as AWS SaaS deployment along with the configuration.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/364

#### Why do we need this ?
To help users set up TTS as AWS SaaS deployment and to troubleshoot the issues.

#### What is already there? What do you see now?
We have TTS available as AWS SaaS deployment

#### What is missing? What do you want to see?
The documentation on deploying The Things Stack as AWS SaaS deployment.

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by benolayinka** [comment]
I don't understand what needs to be updated here. @adriansmares ?

**Comment by i3mSuperMan** [comment]
Hi @adriansmares,

A gentle reminder on this.

**Comment by NicolasMrad** [comment]
what's the status here?

**Comment by michalborkowski96** [comment]
@NicolasMrad I don't really know much about using SaaS, probably @adriansmares would be a better match for this issue

**Comment by adriansmares** [comment]
I will pick this up in Q2.

**Comment by ymgupta** [comment]
Below are the steps and example screenshots for subscribing to the tenant in The Things Stack Cloud deployment via AWS Marketplace:

**Step 1:** Navigate to [The Things Stack Cloud for LoRaWAN](https://aws.amazon.com/marketplace/pp/prodview-djx65iyt6w5cy) in AWS Marketplace. 

![Screenshot 2023-02-18 154807](https://user-images.githubusercontent.com/105837895/219855525-9bb8e8c4-baa3-496f-a298-943e4c3f16a7.png)



**Step 2:** Log in to the AWS account and click on `View purchase options`. Then we will be navigated to the below page and click on `Subscribe`.

![Screenshot 2023-02-18 154940](https://user-images.githubusercontent.com/105837895/219855542-d5de72a2-1b09-4ef6-8060-1deb9184ba0c.png)


**Step 3:** Navigate to the Manage Subscriptions in the AWS Marketplace.

![Screenshot 2023-02-18 155340](https://user-images.githubusercontent.com/105837895/219855593-d7bacbd2-fe32-4e65-8522-e74038131c2c.png)


**Step 4:** In The Things Stack Cloud for LoRaWAN subscription, select the option `Set up product` at the bottom.

![image](https://user-images.githubusercontent.com/105837895/219855608-6a0db5dd-fb85-47ce-90f8-90c04d9508d2.png)


**Step 5:** You will observe a pop up, i.e., `To continue, set up your account and complete the registration`. Then Click on `Set up your account`.

![Screenshot 2023-01-30 210012](https://user-images.githubusercontent.com/105837895/219855640-2b2ba094-e431-4e56-b75b-5c2877985c87.png)


**Step 6:** Fill in all the details on the `Configure your account` page and click on submit.

![Screenshot 2023-01-30 210107](https://user-images.githubusercontent.com/105837895/219855661-51ff37b7-6b4e-43cd-b968-e41fbdba2eb2.png)

After completion of the above steps, users can get the tenant ID and the user details to access The Things Stack.

@nejraselimovic, could you please document the above process to subscribe a tenant via AWS Marketplace in The Things Stack Cloud deployment?

cc: @adriansmares

**Comment by KrishnaIyer** [comment]
@ymgupta: Since you already have all the information and screenshots, why not just open a PR yourself?

**Comment by Siva-7482** [comment]
@KrishnaIyer, we have filed a PR with the above mentioned information and screenshots. Please review.

Ref: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1305

**Comment by ymgupta** [comment]
This is completed in the below PR.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1305
