### ISSUE TITLE
Add information about OAuth client Registration

### ISSUE THREAD

**Issue by romach** [TheThingsIndustries/lorawan-stack-docs#439]
#### Summary

The current version of the documentation contains a statement that we need an OAuth client registration, but it does't contain information, how we can do this.

#### Why do we need this ?

To simplify OAuth client registration.

#### What is already there? What do you see now?

https://www.thethingsindustries.com/docs/reference/api/authentication/#oauth-access-tokens

#### What is missing? What do you want to see?

Add CLI command for creation of the OAuth client

#### How do you propose to document this?

Add CLI command for creation of the OAuth client

#### Can you do this yourself and submit a Pull Request?

Yes

**Comment by johanstokking** [comment]
Thanks @romach for filing this issue.

We're blocking this on Console support: https://github.com/TheThingsNetwork/lorawan-stack/issues/4300

Once we have that, we can still provide an CLI example, but then at least it is less error prone.
