### ISSUE TITLE
Document the type of data that the `license.file` accepts to use the license key

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#444]
#### Summary
Users can specify the license key of their enterprise deployments in the configuration file using below options.
1. `license.key`: Contents of the license key
2. `license.file`: Location of the license file

When setting the license key using `license.key`, a base64 encoded value is used, and TTS would be able to validate the license and run without any issues. However, when we store the license in a file and specify that file path, TTS returns the below error.
```
stack_1 | error:pkg/license:invalid_license (invalid license)
stack_1 | --- proto: illegal wireType 7
stack_1 | error:pkg/license:invalid_license (invalid license)
stack_1 | --- proto: illegal wireType 7
```
This is because, when using `license.file`, the file must contain the raw bytes of the license instead, and not the base64 encoded string.

Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/494

#### Why do we need this?
To let users know how to set the license key when it is stored in a file.

#### What is already there? What do you see now?
The [current documentation](https://www.thethingsindustries.com/docs/reference/configuration/the-things-stack/#license) explains to us the configuration options available to set the license key.

#### What is missing? What do you want to see?
The data type that the `license.file` accepts. And, the commands to create a new file with raw bytes from base64 string.
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/494#issuecomment-875516423

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
@benolayinka

**Comment by benolayinka** [comment]
Does this make sense? Isn't it better to accept base64 in the file
