### ISSUE TITLE
Document an article that describes the Gateway's RTT and its limitations

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#455]
#### Summary
We have observed that the gateways with higher `RTT` values are affecting the downlinks. And one of the reasons for the higher `RTT` values might be the flaky backhaul(internet) connection to the gateways.
#### Why do we need this ?
It would be better if there is more information at Gateways troubleshooting section about Gateway RTT, reasons for the higher RTT values, and its limitation.
#### What is already there? What do you see now?
https://www.thethingsindustries.com/docs/gateways/adding-gateways/troubleshooting/
#### What is missing? What do you want to see?
Document the Gateway's RTT, reasons for the higher RTT values, and its limitation.
#### How do you propose to document this?
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/99#issuecomment-667097069
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/127#issuecomment-696598929
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/203#issuecomment-732141378
https://github.com/TheThingsIndustries/lorawan-stack-support/issues/225#issuecomment-764527572
https://github.com/TheThingsNetwork/lorawan-stack/issues/3515
#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by benolayinka** [comment]
@johanstokking @htdvisser can you give a technical explanation?

**Comment by KrishnaIyer** [comment]
I'll take this issue.
