### ISSUE TITLE
Document about `--ttnv2.resets-to-frequency-plan` flag in the migration docs.

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#481]
#### Summary
Document the `--ttnv2.resets-to-frequency-plan` flag and its usage in the migration documentation.

#### Why do we need this ?
To keep the documentation up to date with the latest changes in the migration tool.

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?
Documentation about the `--ttnv2.resets-to-frequency-plan` flag which was introduced in the latest version of the migrate tool `v0.6.0`.
Ref: https://github.com/TheThingsNetwork/lorawan-stack-migrate/releases/tag/v0.6.0

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
No.

**Comment by ymgupta** [comment]
@nejraselimovic, Reopening this issue to document the below point in the **Migrate Active Sessions** section as well.

> Note:
> Use the --ttnv2.resets-to-frequency-plan flag to configure the factory preset frequencies of the device, so that it can keep working with The Things Stack. The list of uplink frequencies is inferred from the Frequency Plan.
> Ref: https://www.thethingsindustries.com/docs/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/establish-new-session/

We see that the point is mentioned only in the **Migrate without Persisting Active Sessions** section. However, the point is relevant for both cases (Migration with and without Persisting Active Sessions). Hence, please add the Note point in the [**Migrate Active Sessions**](https://www.thethingsindustries.com/docs/getting-started/migrating/migrating-from-v2/migrate-using-migration-tool/migrate-active-session/) section as well.
