### ISSUE TITLE
Documentation about Profile Settings page

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#483]
#### Summary
Document about different options available in the Profile Settings page and how users can make use of them.

#### Why do we need this ?
To let users be aware of how they can change their passwords, Email addresses, etc.

#### What is already there? What do you see now?

...

#### What is missing? What do you want to see?
Documentation of different options that are available in the Profile Settings page.

#### How do you propose to document this?
To add a new section in the `Console` section in `Getting started`.

#### Can you do this yourself and submit a Pull Request?
No

**Comment by benolayinka** [comment]
@nejraselimovic can you pick this one up
