### ISSUE TITLE
Document Gateway location queries in the troubleshooting guide

### ISSUE THREAD

**Issue by i3mSuperMan** [TheThingsIndustries/lorawan-stack-docs#519]
#### Summary
Add below commonly encountered gateway location queries to the troubleshooting guide.
1. GPS location details of the LBS gateway are not shown on the TTS Console
2. GPS location details of the UDP gateway are not shown on the TTS Console
3. Gateway location not surfacing in the GS Service API(connection stats)

#### Why do we need this ?
Adding common queries of Gateway location to the Gateway troubleshooting documentation will be useful for the Users.

#### What is already there? What do you see now?
https://www.thethingsindustries.com/docs/gateways/troubleshooting/

#### What is missing? What do you want to see?
Address the above-mentioned queries in the documentation.

**Insights:**
> 1. GPS location details of the LBS gateway are not shown on the TTS Console
- The LoRa Basics Station protocol does not currently support GPS fields in Uplink messages.
  - Ref1: https://doc.sm.tc/station/tcproto.html
  - Ref2: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/393#issuecomment-818718905
> 2. GPS location details of the UDP gateway are not shown on the TTS Console
- GPS Gateway location details are updated from the status message in the console are supported for only authenticated gateway(BS & MQTT); gateways connected over UDP are not supported in The Things Stack.
- Alternatively, you can update the GPS location details manually in the Console. (i.e., Lat, long,…etc)
  - Navigate to the gateway **location settings** page from The Things Stack Console.
  - Click on the `Save changes` button
  - Reboot/Restart the physical Gateway to see the changes.

> 3.  Gateway location not surfacing in the GS Service API(connection stats)
- The connection statistics or GS service API does not store the gateway location. The location information is stored in the Identity Server, and we allow authenticated Gateways with GPS to update it; gateways connected over UDP are not supported.
- Alternatively, the updated location can be found by querying the Identity Server `GetGateway` [API](https://www.thethingsindustries.com/docs/reference/api/gateway/).

```
curl -H "Authorization: Bearer NNSXS.xxxxxxxxxxxxxx" https://example.thethings.com/api/v3/gateways/<Gateway ID>?field_mask=antennas
```
Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/356#issuecomment-799366993

#### How do you propose to document this?
...

#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by nejraselimovic** [comment]
@i3mSuperMan if updating gateway location from status messages is not supported for LBS and not supported for UDP, for which gateway type is it supported at the end? Only MQTT?
