### ISSUE TITLE
Document The Things Kickstarter Gateway `FAQs` and `Unexpected data send to gateway` error into troubleshooting section.

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#549]
#### Summary
Add common `FAQs` and `Unexpected data send to gateway` error into The Things Kickstarter Gateway troubleshooting section
#### Why do we need this?
Adding `common queries/errors` to The Things Kickstarter Gateway `troubleshooting` section will be useful for the users to debug the issues on their own.
#### What is already there? What do you see now?

- Connecting The Things Kickstarter Gateway to The Things Stack. Ref: https://www.thethingsindustries.com/docs/gateways/thethingskickstartergateway/
- There is FAQs documentation for The Things Kickstarter Gateway here.  Ref: https://www.thethingsnetwork.org/docs/gateways/gateway/faq/ 

#### What is missing? What do you want to see?
Add common FAQs and errors to the[ troubleshooting](https://www.thethingsindustries.com/docs/gateways/thethingskickstartergateway/#troubleshooting) section.
#### How do you propose to document this?
**Insights:**

- Add a note point that the **Gateway ID** in the Kickstarter Gateway configuration allows only a maximum length of `34` characters.

> There is FAQs documentation for The Things Kickstarter Gateway here.  Ref: https://www.thethingsnetwork.org/docs/gateways/gateway/faq/ 

- Reuse the above documentation and update in the troubleshooting section.

> Unexpected data send to gateway error

![image](https://user-images.githubusercontent.com/9304207/131357561-5d46f8f6-2af9-4952-b2ee-6016586f104f.png)

Cause:

- The error could be seen if the length of the `Gateway ID` in the `Gateway configuration page` is larger than the maximum allowed length.

Fact:

- The maximum allowed length for the **Gateway ID** is `34`. Ref: https://github.com/TheThingsProducts/gateway/blob/master/firmware/src/custom_http_app.c#L546

Resolution:

- Cross-check if the length of the Gateway ID in the Gateway configuration page is larger than the allowed maximum length.
- Delete and re-register the gateway in the TTS Console with a shorter Gateway ID. Then, you can use it in configuring the physical gateway.

#### Can you do this yourself and submit a Pull Request?
No. @nejraselimovic

**Comment by nejraselimovic** [comment]
@kschiffer this error seems like something we can improve, right?
