### ISSUE TITLE
Document resolutions for the downlink rejection errors in the Gateway Troubleshooting guide.

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#652]
#### Summary
Document resolutions for the downlink rejection errors in the UDP gateways. For example,  `TOO_LATE`, `TOO_EARLY`, `COLLISION_PACKET`, etc.
#### Why do we need this?
Adding resolutions for the downlink rejection errors to the [Gateway troubleshooting](https://www.thethingsindustries.com/docs/gateways/troubleshooting/#im-noticing-some-errors-in-my-udp-gateways-packet-forwarder-logs-what-do-they-represent) documentation will be useful for the Users.
#### What is already there? What do you see now?
Cause to different downlink rejections at the gateway level.
Ref: https://www.thethingsindustries.com/docs/gateways/troubleshooting/#im-noticing-some-errors-in-my-udp-gateways-packet-forwarder-logs-what-do-they-represent
#### What is missing? What do you want to see?
Resolutions for the downlink rejection errors in the [Gateway Troubleshoot](https://www.thethingsindustries.com/docs/gateways/troubleshooting/#im-noticing-some-errors-in-my-udp-gateways-packet-forwarder-logs-what-do-they-represent) guide.
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by nejraselimovic** [comment]
Could you please provide some input on what those resolutions are?

**Comment by nejraselimovic** [comment]
@adriansmares I've been following the discussion on [this issue](https://github.com/TheThingsNetwork/lorawan-stack/issues/18), so thought you could provide some input here. Are causes of these errors known? Can a user do something on his side to avoid these errors?

**Comment by adriansmares** [comment]
> @adriansmares I've been following the discussion on [this issue](https://github.com/TheThingsNetwork/lorawan-stack/issues/18), so thought you could provide some input here. Are causes of these errors known? Can a user do something on his side to avoid these errors? [This](https://github.com/Lora-net/packet_forwarder/blob/d0226eae6e7b6bbaec6117d0d2372bf17819c438/PROTOCOL.TXT#L420) doesn't say too much.

These errors occur only for the UDP packet forwarder, so my recommandation for anyone seeing `TxPower`/`TxFreq` errors in the gateway events would be to make sure that the `global_conf.json` is in sync - this would signal a configuration error. For the rest of the errors - I would just ask people to contact us, because the chances are quite high that there is a bug with us (or at least some edge case that we could cover for the UDP packet forwarder, since I don't really see any fixes being added to that project nowadays).
