### ISSUE TITLE
Document the data retention period of storage integration

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#659]
#### Summary
The Storage Integration allows storing received upstream messages in a persistent database and retrieving them at a later time. And, it would be good to document the retention period of data in storage integration.
#### Why do we need this?
Users would be informed about the storage retention period and could design their implementations accordingly.
#### What is already there? What do you see now?
Configuration, Enable/Disable, and retrieving of storage integration.
Ref: https://www.thethingsindustries.com/docs/integrations/storage/
#### What is missing? What do you want to see?
The retention period for the data stored in the storage integration of The Things Stack Cloud and The Things Stack Community Edition.

cc: @adriansmares
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No

**Comment by nejraselimovic** [comment]
@adriansmares @KrishnaIyer I saw a few discussion threads about the data rentention period, but I'm not sure what was the conclusion here.
- TTS CE - 24 hours?
- TTSC - 30 days?

**Comment by KrishnaIyer** [comment]
That sounds correct to me.
