### ISSUE TITLE
Improve CLI instructions in Things Join Server documentation

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#669]
#### Summary
While registering a device in the Things Join Server, **CLI Configuration With Cloud Cluster** can be used. Only if a third-party LoRaWAN network is used, the **CLI Configuration With Join Server Only** has to be used.

#### Why do we need this ?
To make the CLI Configuration part more clear to the customers when using Things Join Server.

#### What is already there? What do you see now?
In the Register Devices section, it is mentioned to use a **configuration file with Join Server only**.
Ref: https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/register-devices/#prerequisites

#### What is missing? What do you want to see?

...

#### How do you propose to document this?
Update the CLI Configuration instruction point as below in the Register Devices section as part of the PR [here](https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/667).

> Command-line interface (CLI) [configuration file with Cloud cluster](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/#cli-configuration-with-cloud-cluster). If you are working with a third-party LoRaWAN network, use the Command-line interface (CLI) [configuration file with Join Server Only](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/#cli-configuration-with-join-server-only).

Ref: https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/register-devices/#prerequisites

#### Can you do this yourself and submit a Pull Request?
No

**Comment by nejraselimovic** [comment]
Closed with #667.
