### ISSUE TITLE
Update the documentation to reflect the addition of a new TTSC cluster in London (eu2).

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#691]
#### Summary
Document about the newly added London cluster (eu2) to The Things Stack Cloud deployment.
#### Why do we need this?
It helps users to know about the new cluster in the TTSC deployment and the URL to access it.
#### What is already there? What do you see now?
Information about the existing three clusters (`eu1`, `au1` & `nam1`) and the URLs to access them.
Ref: https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/
#### What is missing? What do you want to see?
Update documentation with respect to the new London (`eu2`) cluster for TTSC. Below are the few places in the documentation where this info needs to be added.
Ref:
https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/
https://www.thethingsindustries.com/docs/getting-started/console/#the-things-stack-cloud
https://www.thethingsindustries.com/docs/getting-started/cli/configuring-cli/#automatically-generate-configuration-file
Thus, please consider checking if this information needs to be updated in any other section in the documentation and update accordingly.
#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by oliveselow** [comment]
#692
