### ISSUE TITLE
Broken MQTT examples

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#711]
#### Summary

From feedback widget:

In the publish example the 'auth' is missing from auth={'username':"app1... leading to a SyntaxError: positional argument follows keyword argument error while compiling. Also the 'context' module seems to be discontinued ?

https://www.thethingsindustries.com/docs/integrations/mqtt/mqtt-clients/eclipse-paho/

**Comment by nejraselimovic** [comment]
hmm, I fixed the auth part, but I can't find any info about the `context` module being discontinued. I double-checked examples to make sure they work, so I think this can be closed for now
