### ISSUE TITLE
Document connecting TTIG in deployments other than TTS CH and CE

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#728]
#### Summary
We need to let users know how to connect TTIG to deployments other than TTS Cloud and Community Edition.

#### Why do we need this ?
...

#### What is already there? What do you see now?
Instructions for connecting TTIG to Cloud and Community Edition.

#### What is missing? What do you want to see?
...

#### How do you propose to document this?
...

#### Can you do this yourself and submit a Pull Request?
@KrishnaIyer

**Comment by KrishnaIyer** [comment]
Done in https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/793
