### ISSUE TITLE
Document the APIs for purging entities

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#765]
#### Summary
Document the purge APIs and also instructions for purging entities using the APIs in the respective sections in the documentation. Ref: https://www.thethingsindustries.com/docs/reference/api/
#### Why do we need this ?
Will be helpful for users to purge the entities using APIs.
#### What is already there? What do you see now?

- APIs to purge entities in [api.swagger.json](https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.18/api/api.swagger.json).
- How to Purge Entities via the Console and CLI is available here. Ref: https://www.thethingsindustries.com/docs/reference/purge/#how-to-purge-entities

#### What is missing? What do you want to see?

- Document the APIs to purge entities here: https://www.thethingsindustries.com/docs/reference/api/.
- An `API` tab in the How to Purge Entities section with instructions and examples on purging entities using the API. Ref: https://www.thethingsindustries.com/docs/reference/purge/#how-to-purge-entities

#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by nejraselimovic** [comment]
Closes with #773
