### ISSUE TITLE
Download page problems

### ISSUE THREAD

**Issue by michalborkowski96** [TheThingsIndustries/lorawan-stack-docs#79]
1. Link 'Download' to open source version is broken.
2. First (and last) row of the table doesn't look good on certain screens (see image). Words are broken where they shouldn't and buttons aren't in one line.

![Screenshot 2020-11-11 at 13 40 27](https://user-images.githubusercontent.com/15948821/98813713-f1422a80-2424-11eb-9daf-bfdd13b6059c.png)

@benolayinka

**Comment by johanstokking** [comment]
Need milestone

**Comment by johanstokking** [comment]
@michalborkowski96 these are two separate issues.

@benolayinka please fix at least the downlink page as part of this milestone.

**Comment by benolayinka** [comment]
Download link was fixed in #167 .
Download page will be replaced by https://thethingsindustries.com/technology/pricing/ or something similar
