### ISSUE TITLE
Improvise the resource limiting docs

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#791]
#### Summary
Some users misunderstood that the resource limits apply to all the applications in a tenant. However, it is not the case. The resource limits defined in the resource limiting profile are for each application in a tenant.

Also, it would be good to document the error cause displayed on TTS Console when the MQTT connections resource-limiting exceeds.

#### Why do we need this ?
1. To help users troubleshoot the issue when their MQTT connections are being rejected.
2. To clarify that the resource limits are per application in a tenant.

#### What is already there? What do you see now?
The [documentation](https://www.thethingsindustries.com/docs/reference/resource-limiting/#example-configuration) contains information to define resource limits for whole deployment, tenant, and per application. Also, it has information about the errors (at the client end) for the new connections when the resource limit exceeds.

#### What is missing? What do you want to see?
1. Emphasize with a note point that the resource limits are per application in a tenant.
2. Document the error cause for the MQTT connection failed events in the console and the resolution. As mentioned in the docs, the resolution for this error would be to terminate existing connections and retry.

Sample Error:
```
Resource limit 16 exceeded for resource with key as:conn:frontend:mqtt:app:test-app-1@test-tenant-1
```

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?
No

**Comment by nejraselimovic** [comment]
As far as I can understand from [here](https://www.thethingsindustries.com/docs/reference/resource-limiting/#example-configuration), resource limiting can be configured per application or for all applications in a tenant
