### ISSUE TITLE
Update The Things Join Server Documentation

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#806]
#### Summary
Based on the latest insights, we have identified a point in [The Things Join Server](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/) documentation that needs to be updated.
1. Add the`--unset version_ids` flag to the CLI command in [Activating Devices on Cloud](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted/) section.
#### Why do we need this?
Currently, the CLI command to update the device configuration does not register the device in the application server resulting in a few issues.
#### What is already there? What do you see now?
CLI command for [Activating Devices on Cloud](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted/#register).
#### What is missing? What do you want to see?
Update the below command in the [Activating Devices on Cloud](https://www.thethingsindustries.com/docs/getting-started/cloud-hosted/tti-join-server/activate-devices-cloud-hosted/) sub page. Ref: https://github.com/TheThingsIndustries/lorawan-stack-support/issues/743
```
ttn-lw-cli end-devices set test-app eui-0004a310001ff9e0 \
  --net-id 000013 \
  --lorawan-version 1.0.2 \
  --lorawan-phy-version 1.0.2-b \
  --frequency-plan-id EU_863_870 \
  --supports-join \
  --unset version_ids \
  --touch
  ```
#### How do you propose to document this?
....
#### Can you do this yourself and submit a Pull Request?
No.

**Comment by nejraselimovic** [comment]
Closed with #805
