### ISSUE TITLE
link to CONTRIBUTING.md is broken on homepage of https://thethingsstack.io/

### ISSUE THREAD

**Issue by hilvarenbeek** [TheThingsIndustries/lorawan-stack-docs#82]
#### Summary
Change link, e.g. to https://github.com/TheThingsNetwork/lorawan-stack/blob/v3.10/CONTRIBUTING.md
Current link https://github.com/TheThingsNetwork/lorawan-stack/blob/default/CONTRIBUTING.md doesn't appear to work.

#### Why do we need this ?
Fix link on homepage, so it's easier to find the document.

#### What is already there? What do you see now?
I get a HTTP 404 GitHub page when following the link.

#### What is missing? What do you want to see?
-

#### How do you propose to document this?
-

#### Can you do this yourself and submit a Pull Request?
could create a pull request to make it link to v3.10, but there might be better alternatives to link to the default branch?

**Comment by benolayinka** [comment]
Closed by https://github.com/TheThingsIndustries/lorawan-stack-docs/commit/58f41ec8dc416312ba83aec01f00f0d8c75e1811
