### ISSUE TITLE
Document connecting Cisco IXM Gateway using Basics Station

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#834]
#### Summary
Cisco supports LoRa Basics Station with the latest firmware. The current documentation doesn't have information on connecting Gateway using LBS with TTS. Ref: https://www.thethingsindustries.com/docs/gateways/ciscowirelessgateway/
#### Why do we need this ?
To connect Gateway with TTS using LBS.
#### What is already there? What do you see now?
Guide on how to connect the Cisco Wireless Gateway to The Things Stack using UDP. Ref: https://www.thethingsindustries.com/docs/gateways/ciscowirelessgateway/
#### What is missing? What do you want to see?

- To connect Cisco Gateway in UDP protocol, **Cisco gateways appear to use a proprietary format, with additional fields for their FPGA**. The instructions on https://www.thethingsindustries.com/docs/gateways/ciscowirelessgateway/ won’t work with our `global_conf.json` file. We need to update the documentation [here](https://www.thethingsindustries.com/docs/gateways/ciscowirelessgateway/#retrieve-configuration-from-the-gateway-configuration-server).

- Add a guide to connecting the Cisco Gateway with TTS using LBS.

#### How do you propose to document this?
...
#### Can you do this yourself and submit a Pull Request?
No. @benolayinka

**Comment by nejraselimovic** [comment]
@ymgupta do you have any useful documentation we can use here? I can't seem to find any guide for using this gateway with LBS

**Comment by ymgupta** [comment]
Hi @nejraselimovic,

There is [documentation](https://www.cisco.com/c/en/us/td/docs/routers/interface-module-lorawan/software/configuration/guide/b_lora_scg/lrr.html#Cisco_Task.dita_a86d318a-6ea7-46d4-b764-b776ad1912ad) from Cisco on configuring the packet forwarder, but it is generic.

Also, The Things Stack supports only [TLS server authentication and client token](https://lora-developers.semtech.com/build/software/lora-basics/lora-basics-for-gateways/?url=authmodes.html) mode at the moment. Cisco added support for this Authentication Mode from the `v2.3.0` release. So, the **gateway should be running with minimum firmware version** [`2.3.0`](https://www.cisco.com/c/en/us/td/docs/routers/interface-module-lorawan/software/release/notes/b_lorawan_rn_2_3_0.html).

**Comment by nejraselimovic** [comment]
I looked into this but I'm afraid I can't do anything here without using the device.

**Comment by KrishnaIyer** [comment]
This is being bounced around a bit. I think @adriansmares or myself can pick it up and run tests with our test gateway.
