### ISSUE TITLE
Remove references to CockroachDB

### ISSUE THREAD

**Issue by htdvisser** [TheThingsIndustries/lorawan-stack-docs#835]
#### Summary

We need to remove references to CockroachDB from the documentation.

#### Why do we need this ?

In https://github.com/TheThingsNetwork/lorawan-stack/pull/4813 we removed CockroachDB from the development tooling of The Things Stack. With that change, we no longer test The Things Stack on CockroachDB, and even though it will probably still work fine, I think it's better to use the same database (PostgreSQL) everywhere.

#### How do you propose to document this?

- Take a look at the current `docker-compose` file in `lorawan-stack` and make the necessary changes to the examples in this repository.
- Test the examples to make sure they still work.
- Remove other references to CockroachDB.

**Comment by benolayinka** [comment]
@nejraselimovic im swamped with conference work so assigning you here. if you need any help ping me.
