### ISSUE TITLE
LR1110 Lora Cloud Integration

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#86]
#### Summary

Documentation for the LoRa Cloud Integration should be in Integrations. It's currently in reference/application-packages.

#### How do you propose to document this?

Integrations/LoRa-Cloud with a guide about using it, and maybe more technical API stuff can stay in reference/application packages (probably not necessary though.)

Also take a look at the storage integration package, these packages should have the same directory structure and organization.

#### Can you do this yourself and submit a Pull Request?

@nejraselimovic w/ @adriansmares

**Comment by johanstokking** [comment]
Need milestone

**Comment by nejraselimovic** [comment]
@benolayinka can I just add a **LoRa Cloud Integration** section and point to this https://www.thethingsindustries.com/docs/integrations/lr1110-geolocation/ example?

**Comment by benolayinka** [comment]
> @benolayinka can I just add a **LoRa Cloud Integration** section and point to this https://www.thethingsindustries.com/docs/integrations/lr1110-geolocation/ example?

This should be closed by the LR1110 integration you wrote. All done!

**Comment by benolayinka** [comment]
Closed by #165
