### ISSUE TITLE
Improve the troubleshooting CLI guide

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#862]
#### Summary
Getting the following error while using the CLI (installed as a snap package) on `Ubuntu 18.04.6 LTS`.
```
internal error, please report: running "ttn-lw-stack.ttn-lw-cli" failed: cannot create transient scope: DBus error "System.Error.E2BIG": [Argument list too long]
```
FTR, only one user reported this case as of now.
#### Why do we need this ?
It will be useful for the users to troubleshoot CLI issues on their own.
#### What is already there? What do you see now?
[Troubleshooting CLI](https://www.thethingsindustries.com/docs/getting-started/cli/troubleshooting/).
#### What is missing? What do you want to see?
Document the above error in the troubleshooting CLI guide.
#### How do you propose to document this?
**Insights:**

> internal error, please report: running "ttn-lw-stack.ttn-lw-cli" failed: cannot create transient scope: DBus error "System.Error.E2BIG": [Argument list too long]

The error may occur if there is a problem with the snap utility on the computer (Desktop/Laptop). **Downloading and using the CLI binaries directly resolved the issue here.**
#### Can you do this yourself and submit a Pull Request?
No. @nejraselimovic.

**Comment by nejraselimovic** [comment]
Since (based on forum threads like [this one](https://forum.snapcraft.io/t/dbus-error-system-error-e2big-error/29227)) this doesn't appear to be issue with TTS CLI, I'm going to close this without any action. I don't think we need to address issues like these, as there is gazillion system-related issues that one can experience.
