### ISSUE TITLE
Document about the Forgot password option in TTS

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#871]
#### Summary
Document the step-by-step process for resetting the password if the user has forgotten the password of his TTS account.
#### Why do we need this?
It will be helpful to set a new password when the user forgets the password.
#### What is already there? What do you see now?
...
#### What is missing? What do you want to see?
Process for setting a new password when the User forgets the password.
#### How do you propose to document this?
Below are the process steps:
1. Navigate to the Console login page (i.e, https://thethings.example.com/).
2. Click on the `Forgot password?` button.
3. Enter the `User ID` of the account to receive an email with the reset instructions to the account Email ID.
   **Note:** Please check the spam folder as well if you don't see the email in your Inbox.
4. Follow the Reset instructions mentioned in the email.
#### Can you do this yourself and submit a Pull Request?
No

**Comment by nejraselimovic** [comment]
I'm closing this because it seems totally unnecessary.
