### ISSUE TITLE
Document RAK 7240

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#92]
#### Summary

Document connecting RAK 7240

#### Why do we need this ?

Document popular gateways

**Comment by benolayinka** [comment]
@nejraselimovic can you pick this up? i'll send RAK a message for their documentation, it should just be a matter of converting it to a markdown doc

**Comment by nejraselimovic** [comment]
> @nejraselimovic can you pick this up? i'll send RAK a message for their documentation, it should just be a matter of converting it to a markdown doc

Sure, tell me when you have it

**Comment by descartes** [comment]
https://docs.rakwireless.com/Product-Categories/WisGate/RAK7240/Overview/

**Comment by benolayinka** [comment]
> > @nejraselimovic can you pick this up? i'll send RAK a message for their documentation, it should just be a matter of converting it to a markdown doc
> 
> Sure, tell me when you have it

RAK never responded. You can probably just put together something based on this document -> https://docs.rakwireless.com/Knowledge-Hub/Learn/WEB-Management-Platform/#basic-station

Specify instructions for Basic Station, based on our Basic Station docs.

**Comment by i3mSuperMan** [comment]
@benolayinka,

We believe connecting below RAK Model Gateways with the TTSC process is the same.

- RAK7258
- RAK7249
- RAK7240

Ref: https://docs.rakwireless.com/Knowledge-Hub/Learn/WEB-Management-Platform/#basic-station

It would be helpful if you can add **NOTE** on `RAK7258` and `RAK7249` configurations in the `RAK7240` guide.
