### ISSUE TITLE
Document Tektelic with Basic Station

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#93]
#### Summary

Document connecting Tektelic Basic Station

#### Why do we need this ?

Document popular gateways

**Comment by NicolasMrad** [comment]
@benolayinka what's the status for this?

**Comment by benolayinka** [comment]
This is done here https://www.thethingsindustries.com/docs/gateways/tektelickonamicro/lbs/
