### ISSUE TITLE
Update API documentation

### ISSUE THREAD

**Issue by nejraselimovic** [TheThingsIndustries/lorawan-stack-docs#957]
#### Summary
There are some API services and messages missing from the [API documentation](https://www.thethingsindustries.com/docs/reference/api/), so we need to update it.

#### Can you do this yourself and submit a Pull Request?
Yes

**Comment by KrishnaIyer** [comment]
Is this related to https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1185?

**Comment by nejraselimovic** [comment]
> Is this related to #1185?

Yes, that PR should cover this

**Comment by nejraselimovic** [comment]
> > Is this related to #1185?
> 
> Yes, that PR should cover this when finished
