### ISSUE TITLE
Link Enterprise Licensing and Pricing page

### ISSUE THREAD

**Issue by benolayinka** [TheThingsIndustries/lorawan-stack-docs#96]
#### Summary

Link to page where users can get license for Enterprise. Leftover issue from

https://github.com/TheThingsIndustries/lorawan-stack/issues/2202#issuecomment-685616589

#### Can you do this yourself and submit a Pull Request?

@ajovertoom when the pricing / license page is ready

**Comment by ajovertoom** [comment]
This was done in https://github.com/TheThingsIndustries/subscription-management/issues/173
