### ISSUE TITLE
Update documentation for new end device onboarding

### ISSUE THREAD

**Issue by kschiffer** [TheThingsIndustries/lorawan-stack-docs#965]
#### Summary
With the new 3.22 release, the device onboarding has changed which needs to be reflected in our documentation as well.

#### What is already there? What do you see now?
Documentation for the old onboarding flow.

#### What is missing? What do you want to see?
Updated screenshots and descriptions.

#### How do you propose to document this?
The process now is not fundamentally different, it just needs to be updated. One new concept is the QR-code scanning feature which should be documented in its own section.

#### Can you do this yourself and submit a Pull Request?
I planned on doing this myself but I need to reprioritize to make progress with the new billing flow.

**Comment by nejraselimovic** [comment]
@kschiffer why does `Learn more` button next to the `Scan end device QR code` in the Console lead to `https://www.thethingsindustries.com/docs`?
