### ISSUE TITLE
Clicking on the left or right image padding will open a broken image icon in lightbox

### ISSUE THREAD

**Issue by pradeeka7** [TheThingsIndustries/lorawan-stack-docs#979]
#### Summary

Clicking on the left or right image padding will open a broken image icon in lightbox.

#### Why do we need this ?

Only the image should be clickable.

#### What is already there? What do you see now?

![image](https://user-images.githubusercontent.com/36432168/196342587-e94818e1-adf6-4b80-b879-52a0ef345a1d.png)

#### What is missing? What do you want to see?

Remove the clickable padding areas.

#### How do you propose to document this?

...

#### Can you do this yourself and submit a Pull Request?

...

**Comment by nejraselimovic** [comment]
@NicolasMrad  I'm pretty sure this is a job for me, maybe Ben or someone who does frontend
