### ISSUE TITLE
ttn-lw-cli quick start tutorial and reference leave user stuck with error: no_application_id (no application ID set)

### ISSUE THREAD

**Issue by kairoswater-jason** [TheThingsIndustries/lorawan-stack-docs#981]
Hi,

I am a totally new user to TTN's CLI. In short: I find myself unable to find a critical piece of information in the documentation: how to set the application_id in the V3 TTN cli application `ttn-lw-cli`.

Do any tutorials, beyond the (seemingly incomplete?) quick start guide, exist showing how to get `ttn-lw-cli` in a state where is able to perform operations on a specific device?

Background: My original goal was to try to reset the Nonce counter on a particular device that I am developing - which is a cli only operation (`ttn-lw-cli end-devices set command --resets-join-nonces`). But in order to do that I have to get the cli application correctly configured.

I followed the cli quick start and consulted the cli reference. After that, when I issue commands to 
```
$ ttn-lw-cli end-devices list

error:cmd/ttn-lw-cli/commands:no_application_id (no application ID set)
    correlation_id=f6c7cd424469411bb43ab65768f0e1df
```

In TTN V2 the cli has a command called `ttnctl applications select` however in TTN V3's cli application `ttn-lw-cli` there is not such command that I can find. The lack of search function in the online cli reference is also troublesome.

Perhaps I have missed something in the documentation?

Edit: after a bit more digging there are two issues. Difficult to navigate documentation and a misleading error message in the CLI. I was missing a command line argument, although the error message did not indicate that, and documentation provided no help for understanding this particular error condition. I still believe the documentation is capable of improvement. At the very least a link to a tutorial showing basic usage of the TTN V3 cli app (after the quick start) would be helpful for newcomers like me.

**Comment by nejraselimovic** [comment]
The [CLI reference for the `list` command](https://www.thethingsindustries.com/docs/ttn-lw-cli/ttn-lw-cli_end-devices_list/) states the following format: 

`ttn-lw-cli end-devices list [application-id] [flags]`

where you can see that the application ID should be passed as a command line argument. I also find that the error attached above wasn't misleading, you were indeed missing an application ID.

@NicolasMrad I guess we could add a link to one of Ben's videos to make things easier. Can you please create an issue?
