### ISSUE TITLE
Improve Gateway troubleshooting guide

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#987]
#### Summary
Additions to Gateway troubleshooting guide:
1. My gateway backhaul (cellular, Ethernet, or WiFi) consumes a lot of data. How do I optimize it?
2. My gateways are receiving all other LoRaWAN traffic and non-LoRaWAN traffic from the devices in its vicinity. How to filter the unregistered sensors data at the gateway level?
3. I'm seeing "Gateway missed too many pongs” warnings in the gateway live events. What is causing this?

#### Why do we need this?
Adding common queries on Gateways to the Gateway troubleshooting documentation will be useful for the Users.

#### What is already there? What do you see now?
[Troubleshooting Gateways
](https://www.thethingsindustries.com/docs/gateways/adding-gateways/troubleshooting/)

#### What is missing? What do you want to see?
Address the above-mentioned queries in the documentation.

**Insights:**

> 1. My gateway backhaul (cellular, Ethernet, or WiFi) consumes a lot of data. How do I optimize it?

Gateway data consumption is influenced by various factors such as:

- LoRaWAN traffic from all the devices in its vicinity - more the devices/traffic, more the volume.
- Based on the protocol in use and its functionality, the data consumption might vary. For example, a gateway might be sending a status update every N seconds, polling the network server for downstream messages (look for Pull_Data and Pull_Ack in the packet forwarder logs). You can check the factors that consume data according to the protocol used in the gateways.
    - UDP: [PROTOCOL.TXT](https://github.com/Lora-net/packet_forwarder/blob/master/PROTOCOL.TXT)
    - Basics Station: [Welcome! — Basic Station 2.0.5 June 2020 documentation](https://doc.sm.tc/station/)
- If there is a gateway management system running on the gateway, this might use some data volume.
- Any other applications or integrations configured in the gateway consume data too. Check if you have any additional features enabled and optimize accordingly. Example; **Automatic Data Recovery**, **MQTT Bridge**,...etc
- Firmware upgrades, if any.

We recommend contacting the Gateway manufacturer to gather insights on the data consumption, and how it can be optimised further.

---

> 2. My gateways are receiving all other LoRaWAN traffic and non-LoRaWAN traffic from the devices in its vicinity. How to filter the unregistered sensors data at the gateway level?

In general, a gateway will receive all other LoRaWAN traffic and non-LoRaWAN traffic from the devices in its vicinity and forwards it to the Network Server. Regarding filtering of the unregistered sensors data at the gateway level, below are possibilities:
- For [Basics Station](https://www.thethingsindustries.com/docs/gateways/lora-basics-station/) gateways, we have an open issue on GitHub to configure the NetIDs to filter the device addresses that the Gateway will forward to the stack. Ref: https://github.com/TheThingsNetwork/lorawan-stack/issues/3909
- Also, users might consider using a gateway with a whitelisting function that filters unnecessary data from other devices in the vicinity and only forwards what is necessary to you. This function can effectively reduce data traffic and operational costs. Please contact the Gateway manufacturer in case of any further queries in this regard.

---

> 3. I'm seeing "Gateway missed too many pongs” warnings in the gateway live events. What is causing this?

The reported error could be due to the below.

The Gateway server disconnects LoRa Basics Station gateways that stop sending pongs to server ping, it will get disconnected only after missing at least 2 Pongs. Gateways which doesn't send pongs to server ping will face issues. The Things Stack will not take any actions for those gateways which doesn't send pongs. However, it is always recommended for the gateway vendors to support WS pong. Ref: https://github.com/TheThingsNetwork/lorawan-stack/pull/4859 (refer to the Changes section to see the implementation at the TTS level)

#### How do you propose to document this?
...

#### Can you do this yourself and submit a Pull Request?
No, @nejraselimovic

**Comment by nejraselimovic** [comment]
> For [Basics Station](https://www.thethingsindustries.com/docs/gateways/lora-basics-station/) gateways, we have an open issue on GitHub to configure the NetIDs to filter the device addresses that the Gateway will forward to the stack. Ref: https://github.com/TheThingsNetwork/lorawan-stack/issues/3909

We don't really want this in our documentation. When this is implemented, we can add it then.
