### ISSUE TITLE
Document connecting a generic node in TTS 

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#988]
#### Summary
Document how to configure and connect generic node in The Things Stack.

#### Why do we need this ?
To assist users in configuring and connecting the generic node to The Things Stack.

#### What is already there? What do you see now?
- [The Things Industries documentation on devices](https://www.thethingsindustries.com/docs/devices/)
- [Generic Node documentation](https://www.genericnode.com/docs/)
#### What is missing? What do you want to see?
A guide to configure and connect the generic node to TTS in the device guide. Ref: https://www.thethingsindustries.com/docs/devices/

#### How do you propose to document this?
...

#### Can you do this yourself and submit a Pull Request?
No, @nejraselimovic

**Comment by pradeeka7** [comment]
> @NicolasMrad can you assign someone who owns a generic node to document this?

@NicolasMrad I can work on this.

**Comment by nejraselimovic** [comment]
> > @NicolasMrad can you assign someone who owns a generic node to document this?
> 
> @NicolasMrad I can work on this.

That would be great @pradeeka7, thanks!

**Comment by pradeeka7** [comment]
I have submitted a PR for this: https://github.com/TheThingsIndustries/lorawan-stack-docs/pull/1037

**Comment by pradeeka7** [comment]
@NicolasMrad Can you close this issue?
